# === Graph Settings ===

# === Dataset Settings ===
dataset:
  # path: "outage_dataset"  # Path to adjacency matrix (.npy file)
  # path: "outage_dataset_noisy"
  path: "outage_dataset_noisy2"
  # path: "C:/Users/nadav/OneDrive - Technion/technion/ProjectB/Code/outage_dataset_white_noise"
  network_name: "ieee14"  # Change this to the desired network name
  graph_path: "graph.npy"
  metadata_path: "meta.json"
  test_size: 0.1         # Fraction of data to be used for testing
  cal_size : 0.2         # Fraction of data to be used for calibration

# === Model Settings ===
load_pretrained: True  # Load pretrained model weights
params_path: "Model/params.pth"

# === Spectral Convolution ===
output_features: 20           # G: Number of spectral filters (output features)
poly_order: 1                 # H: Degree of the frequency-domain polynomial filter

# === Training ===
batch_size: 16
num_epochs: 80
learning_rate: 0.01
lr_decay: 0.9                 # Exponential learning rate decay - CURRENTLY NOT USED

# === Conformal Prediction ===
Conformal:
  alpha: 0.1             # Significance level for conformal prediction
  topk: 3                # Number of top predictions to consider
  

# from now on - CURRENTLY NOT USED

# === Optimization ===        
optimizer: "adam"
loss_function: "cross_entropy"

# === Model ===
use_activation: False          # Apply nonlinearity after convolution
classifier_type: "linear"     # Linear layer after flattening
num_classes: 1                # Binary classification (1 = line out, 0 = no outage)

# === Regularization ===
dropout: 0.0                  # Not used in the paper but you could experiment with this

# === Evaluation ===
metrics:
  - precision
  - recall
  - f1_score